### ISSUE TITLE
Unable to load the model

### ISSUE THREAD

**Issue by tuotuoZ** [GU-DataLab/stance-detection-KE-MLM#1]
Hi, I am facing an issue when trying to load the model in Colab. I used the git clone to download all the files.
![image](https://user-images.githubusercontent.com/40042621/117365805-d4475b00-ae8d-11eb-97e5-ddb5204694ad.png)

Also, the download by model name is not working for your model from my testing. Here is a screenshot when trying using the model name instead of the file path.
![image](https://user-images.githubusercontent.com/40042621/117366022-2b4d3000-ae8e-11eb-9c08-276d1947c07a.png)

**Comment by tuotuoZ** [comment]
I am also very interested in reading your paper. Is it available now?

**Comment by kornosk** [comment]
@tuotuoZ Hi. I think the first image, you need to put `kornosk/` as the prefix for the model path. For the second image, you need to set `from_tf=False` or just remove the param since the default is false. Our models were trained with PyTorch, the param `from_tf` is used when the model is trained with TensorFlow.

Let us know if you have any other issues. 👍

**Comment by kornosk** [comment]
> I am also very interested in reading your paper. Is it available now?

@tuotuoZ  We will inform you once it is available. Probably next week.

**Comment by tuotuoZ** [comment]
Hi Kornosk, thanks for your reply. I copied the exact code from Github. Here is what I got:
![image](https://user-images.githubusercontent.com/40042621/117555344-66856580-b02c-11eb-8bc0-611e29d663b0.png)

**Comment by kornosk** [comment]
@tuotuoZ Can you check the dependencies `pytorch==1.8.1` and `transformers==4.5.1`? I checked my code with these dependencies.

If it still doesn't work, try removing `tensorflow`. I think this issue happened to me before.

**Comment by tuotuoZ** [comment]
thanks! Removing the tensorflow libaray solved the problem!

**Comment by kornosk** [comment]
> I am also very interested in reading your paper. Is it available now?

@tuotuoZ The paper is available online now at [https://www.aclweb.org/anthology/2021.naacl-main.376](https://www.aclweb.org/anthology/2021.naacl-main.376/).

**Comment by tuotuoZ** [comment]
> > I am also very interested in reading your paper. Is it available now?
> 
> @tuotuoZ The paper is available online now at [https://www.aclweb.org/anthology/2021.naacl-main.376](https://www.aclweb.org/anthology/2021.naacl-main.376/).

Yeah, I can see it. THanks!
